### PR TITLE
Use wasm-pack-npm to install rust and wasm-pack

### PR DESCRIPTION
**Pull request by lulu-berlin**
This uses [wasm-pack-npm](https://github.com/robertohuertasm/wasm-pack-npm) to install rust and wasm-pack. This way the CI build can be simplified.

### CODE REVIEW

**Comment by lulu-berlin** [comment]
For some reason, the build hangs when `wasm-pack-npm` tries to install cargo-generate.

**Comment by robertohuertasm** [comment]
@yever, I'm removing `cargo-generate` from the installation. I think it's maybe overkilling. It takes a lot of time and not everybody needs it. I'm preparing a new version.

**Comment by lulu-berlin** [comment]
@robertohuertasm Thanks!

**Comment by robertohuertasm** [comment]
New version ready! Let me know if it works for you.

**Comment by lulu-berlin** [comment]
Yes, I saw. I'm testing it now.

**Comment by lulu-berlin** [comment]
Seems like if `rust` and `wasm-pack` already exist, it skips setting the default toolchain which makes `wasm-pack` fail.

**Comment by lulu-berlin** [comment]
@robertohuertasm Why did you remove setting the default toolchain to nightly as part of the same commit where your removed installing cargo-generate?
https://github.com/robertohuertasm/wasm-pack-npm/commit/3845e4e3fe552df271231f795ffe71d45675faab ("no nightly, no cargo-generate")

**Pull request merged**
